version: '2'
services:
    pharmacrm-app:
        image: pharmacrm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pharmacrm-postgresql:5432/pharmacrm
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pharmacrm-elasticsearch:9300
        ports:
            - 8080:8080
    pharmacrm-postgresql:
        extends:
            file: postgresql.yml
            service: pharmacrm-postgresql
    pharmacrm-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pharmacrm-elasticsearch
